### ISSUE TITLE
Inline encoder/decoder

### ISSUE THREAD

**Issue by akssri** [marijnh/ieee-floats#8]
Inlining the encoder/decoder functions seems like a good idea, since these will likely form the kernel inside function loop. Doing this gives rise to these strange test failures,
```lisp
M> (eos:run! :ieee-floats)
................f.....................f...........
 Did 50 checks.
    Pass: 48 (96%)
    Skip: 0 ( 0%)
    Fail: 2 ( 4%)

 Failure Details:
 --------------------------------
 SPECIALS-64 []: 
      (DECODE-FLOAT64* 9223372036854775808) evaluated to -0.0d0, which is not EQL to -0.0d0..
 --------------------------------
 --------------------------------
 SPECIALS-32 []: 
      (DECODE-FLOAT32* 2147483648) evaluated to -0.0, which is not EQL to -0.0..
 --------------------------------
```

I'm not entirely sure what is wrong.

**Comment by marijnh** [comment]
Those do look very suspicious. Do they occur on multiple implementations, or did you only test one? I'm not actively maintaining this, so when it comes to debugging it in detail, you're on your own.

**Comment by akssri** [comment]
Yeah, it looks like this is a bug in SBCL.

**Comment by akssri** [comment]
This was a bug in SBCL; has been fixed upstream.
